image: "bitnami/express"

stages:
 - build
 - test
 - publish
 - deploy

configuracoes:
 stage: build
 script:
  - npm install
  - node app.js &

testes:
 stage: test
 script:
  - npm install
  - node app.js &
  - npm test
 
publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/tiagorockenbach/teste:devops .
    - docker push registry.gitlab.com/tiagorockenbach/teste

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull registry.gitlab.com/tiagorockenbach/teste:devops
    - docker run -d -p 3000:3000 registry.gitlab.com/tiagorockenbach/teste:devops
  tags:
    - deploy